const PRICING_CREDITS = {
  PRODUCT_CREATE: {
    AI_HANDLE: 5,
    MANUAL_HANDLE: 5,
    REGENERATE: 1,
  },
  PRODUCT_ENHANCEMENT: {
    PER_PRODUCT: 3,
    REGENERATE: 1,
  },
};

const PRICING_PLAN = {
  FREE: "free",
  PRO: "pro",
  UNLIMITED: "unlimited",
};

const PLAN_LIMIT_PRODUCT_CREATE = {
  [PRICING_PLAN.FREE]: 10,
  [PRICING_PLAN.PRO]: 100,
  [PRICING_PLAN.UNLIMITED]: Infinity,
};

const PLAN_LIMIT_PRODUCT_ENHANCEMENT = {
  [PRICING_PLAN.FREE]: 10,
  [PRICING_PLAN.PRO]: 100,
  [PRICING_PLAN.UNLIMITED]: Infinity,
};


export { PRICING_CREDITS, PRICING_PLAN, PLAN_LIMIT_PRODUCT_CREATE, PLAN_LIMIT_PRODUCT_ENHANCEMENT };